/* =====================================================
   OMNIMIND — canonical dataset
   Single source of truth for every tool, category, stack.
   Pages render from this file.
   ===================================================== */

const CATEGORIES = [
  { slug:'chatbots',   icon:'🧠', name:'Chatbots & LLMs',         tagline:'Frontier models you can talk to.',
    desc:'General-purpose AI assistants — the systems that can reason, write, code, and converse across nearly any domain.' },
  { slug:'agents',     icon:'🤖', name:'Agents & Frameworks',     tagline:'AIs that take action.',
    desc:'Autonomous systems and the frameworks that build them — from end-user agents that browse and execute tasks to developer toolkits for orchestrating multiple models.' },
  { slug:'image',      icon:'🎨', name:'Image Generation',        tagline:'From prompt to picture.',
    desc:'Models and apps that turn text and references into stills — covering photorealism, illustration, branding, and concept art.' },
  { slug:'video',      icon:'🎬', name:'Video Generation',        tagline:'Moving pictures from text.',
    desc:'AI video — text-to-video, image-to-video, motion control, and avatar systems. The fastest-evolving category in AI.' },
  { slug:'music',      icon:'🎵', name:'Music & Audio',           tagline:'Songs, scores, and sound design.',
    desc:'Music generation, scoring, and audio production — from full songs with vocals to game-ready adaptive scores.' },
  { slug:'voice',      icon:'🗣️', name:'Voice & Speech',          tagline:'Speech you can’t tell from human.',
    desc:'Text-to-speech, voice cloning, real-time conversational voice, and the new wave of phone-call agents.' },
  { slug:'coding',     icon:'💻', name:'Coding & Developer',      tagline:'AI for people who ship.',
    desc:'IDEs, terminal agents, code review, and full-stack app builders — the tools senior engineers actually keep open.' },
  { slug:'search',     icon:'🔎', name:'Search & Research',       tagline:'Answers, not ten blue links.',
    desc:'AI answer engines, deep-research agents, and grounded knowledge tools that cite their sources.' },
  { slug:'writing',    icon:'📝', name:'Writing & Productivity',  tagline:'Words, notes, and meetings.',
    desc:'Long-form writing, marketing copy, note-taking, and meeting intelligence — productivity AI that actually saves hours.' },
  { slug:'design',     icon:'✏️', name:'Design & Creative',       tagline:'Design at the speed of thought.',
    desc:'AI-native design tools, slide decks, websites, and the new generation of prompt-to-UI systems.' },
  { slug:'business',   icon:'💼', name:'Business & Automation',   tagline:'AI for the real economy.',
    desc:'Workflow automation, sales intelligence, legal AI, and the systems running operations at scale.' },
  { slug:'infra',      icon:'🧪', name:'Infra & Platforms',       tagline:'The plumbing of modern AI.',
    desc:'Model hubs, vector databases, inference platforms, and the developer infrastructure that powers everything else.' },
];

const TIERS = {
  frontier:   { label:'Frontier',    desc:'The absolute top of its category — defines the state of the art.' },
  leading:    { label:'Leading',     desc:'Excellent, widely adopted, near-frontier.' },
  specialist: { label:'Specialist',  desc:'Best-in-class for a specific use case.' },
  open:       { label:'Open-source', desc:'Self-host or free-tier champions.' },
};

const TOOLS = [
  /* ============= CHATBOTS & LLMs ============= */
  { slug:'claude', name:'Claude', maker:'Anthropic', cat:'chatbots', tier:'frontier',
    pricing:'Free · $20/mo · $100–$200 Max', url:'https://claude.ai',
    blurb:'Best reasoning, writing, and coding. The thinking person’s chatbot.',
    summary:'Anthropic’s flagship line — Opus 4.7, Sonnet 4.6, and Haiku 4.5 — leads on serious coding (Opus broke 80% on SWE-bench Verified), long-form reasoning, and prose. Long context, native tool use, computer use, and an in-product memory feature. Available via web, mobile, desktop apps, and the Claude API.',
    strengths:['State-of-the-art coding agent','Excellent long-form reasoning','Honest about uncertainty','Beautiful default writing voice','Strong tool use and computer use'],
    weaknesses:['No native image generation','Tighter free-tier rate limits than ChatGPT','Less plugged into a search index'],
    bestFor:'Engineers, writers, researchers, lawyers',
    alternatives:['chatgpt','gemini','deepseek'] },

  { slug:'chatgpt', name:'ChatGPT', maker:'OpenAI', cat:'chatbots', tier:'frontier',
    pricing:'Free · $20/mo · $200/mo Pro', url:'https://chatgpt.com',
    blurb:'Biggest ecosystem, best all-rounder. The default answer for most people.',
    summary:'OpenAI’s ChatGPT remains the broadest product in AI: GPT-5 and o-series reasoning models, native image generation, voice mode, Canvas, Search, the Operator agent, and a vast custom-GPT store. The default first install for almost anyone trying AI.',
    strengths:['Largest ecosystem and integrations','Excellent voice mode','Native image and chart generation','Operator agent for web tasks'],
    weaknesses:['Quality varies by mode','Memory can drift across sessions','Some features locked to Pro tier'],
    bestFor:'Generalists, students, knowledge workers',
    alternatives:['claude','gemini','grok'] },

  { slug:'gemini', name:'Gemini', maker:'Google DeepMind', cat:'chatbots', tier:'frontier',
    pricing:'Free · $19.99/mo · $249.99 Ultra', url:'https://gemini.google.com',
    blurb:'1M-token context and Workspace integration. Google’s trump card.',
    summary:'Gemini 2.5 / 3 Pro brings a one-million-token context window, native multimodality, and deep ties to Gmail, Docs, Sheets, and YouTube. Deep Research and the Veo / Imagen integrations make it the best-value frontier subscription if you live in Google Workspace.',
    strengths:['Massive 1M-token context','Tight Workspace and Gmail integration','Bundled Veo, Imagen, NotebookLM','Strong multilingual coverage'],
    weaknesses:['Personality blander than Claude or Grok','Some answers err toward over-cautious'],
    bestFor:'Anyone living in Google Workspace',
    alternatives:['chatgpt','claude','notebooklm'] },

  { slug:'grok', name:'Grok', maker:'xAI', cat:'chatbots', tier:'leading',
    pricing:'Free on X · $30/mo · $300 Heavy', url:'https://grok.com',
    blurb:'Real-time X data and a saltier tone. Good for news-adjacent questions.',
    summary:'Grok 4 from xAI ships inside X and as a standalone app. Strong at real-time information thanks to live X access, with a deliberately less filtered voice. Heavy tier exposes long-running agents and image / video generation.',
    strengths:['Real-time access to X / news','Less hedged tone','Image and video generation included'],
    weaknesses:['Tightly coupled to X ecosystem','Less reliable on careful reasoning than Claude or GPT-5'],
    bestFor:'News junkies, traders, X-native users',
    alternatives:['chatgpt','perplexity','gemini'] },

  { slug:'meta-ai', name:'Meta AI', maker:'Meta', cat:'chatbots', tier:'leading',
    pricing:'Free', url:'https://www.meta.ai',
    blurb:'Llama 4 everywhere Meta lives. Free, competent, convenient.',
    summary:'Meta AI is the consumer face of the Llama family — embedded in WhatsApp, Instagram, Messenger, Ray-Ban Meta, and at meta.ai. Free, fast, and good at quick tasks; image generation and voice are bundled in.',
    strengths:['Genuinely free','Built into apps people already use','Decent image generation'],
    weaknesses:['Not on the frontier for reasoning','Limited tool use','Privacy posture is Meta’s'],
    bestFor:'Casual chat inside WhatsApp / Instagram',
    alternatives:['chatgpt','gemini','deepseek'] },

  { slug:'deepseek', name:'DeepSeek', maker:'DeepSeek', cat:'chatbots', tier:'leading',
    pricing:'Free · API from $0.27/M', url:'https://chat.deepseek.com',
    blurb:'Open weights, shockingly capable, a fraction of frontier prices.',
    summary:'DeepSeek’s V3.x and R1-style reasoning models compete with frontier labs at a tiny fraction of the API cost, with open weights for self-host. The chat product is free; the API is the cheapest way to get near-GPT quality at scale.',
    strengths:['Frontier-adjacent quality at low cost','Open weights','Excellent at math and code'],
    weaknesses:['Hosted in China — data residency matters for some','Less polished UX than ChatGPT'],
    bestFor:'Builders shipping AI features at scale',
    alternatives:['claude','chatgpt','qwen'] },

  { slug:'mistral', name:'Mistral Le Chat', maker:'Mistral', cat:'chatbots', tier:'specialist',
    pricing:'Free · €14.99/mo Pro', url:'https://chat.mistral.ai',
    blurb:'European, privacy-leaning, fast. The continental alternative.',
    summary:'Le Chat is Mistral’s consumer assistant — fast, EU-hosted, and built on the Mistral Large family with code interpreter, web search, and image generation via FLUX. Pro tier is good value.',
    strengths:['EU data residency','Very fast responses','Bundled image gen via FLUX'],
    weaknesses:['Not at the absolute frontier','Smaller plugin ecosystem'],
    bestFor:'European teams, privacy-leaning users',
    alternatives:['claude','chatgpt','gemini'] },

  { slug:'qwen', name:'Qwen', maker:'Alibaba', cat:'chatbots', tier:'specialist',
    pricing:'Free · Open weights', url:'https://chat.qwen.ai',
    blurb:'Strong multilingual, open-weights family. Under-rated in the West.',
    summary:'Alibaba’s Qwen3 family covers chat, vision, code, and audio with strong open-weight releases up to 500B+ parameters. Best-in-class for non-English work and a popular base for fine-tuning.',
    strengths:['Excellent multilingual quality','Open weights','Vision and audio variants'],
    weaknesses:['Western product polish lags','Hosted version requires Alibaba account'],
    bestFor:'Multilingual builders, fine-tuners',
    alternatives:['deepseek','claude','huggingface'] },

  { slug:'kimi', name:'Kimi K2', maker:'Moonshot', cat:'chatbots', tier:'specialist',
    pricing:'Free', url:'https://kimi.com',
    blurb:'Long-context champion. Hand it the whole book, then ask.',
    summary:'Moonshot’s Kimi K2 is built for very long context — feed it whole books, codebases, or research archives and ask follow-ups. Strong at retrieval-style work where most models start to blur.',
    strengths:['Massive context handling','Free to use','Good at retrieval-heavy tasks'],
    weaknesses:['Smaller community, fewer integrations','Reasoning behind frontier'],
    bestFor:'Researchers, archivists, anyone with very long documents',
    alternatives:['claude','gemini','notebooklm'] },

  { slug:'ollama', name:'Ollama', maker:'Ollama', cat:'chatbots', tier:'open',
    pricing:'Free', url:'https://ollama.com',
    blurb:'Run any open LLM on your own hardware. No keys, no vendors, no leaks.',
    summary:'Ollama is the simplest way to run open-weight models locally — Llama, Qwen, Mistral, DeepSeek, Phi, and dozens more. One command pulls and serves a model with an OpenAI-compatible API. Pairs cleanly with the Ollama desktop app and integrations like Open WebUI.',
    strengths:['One-command local model runtime','OpenAI-compatible API','Privacy: nothing leaves your machine'],
    weaknesses:['Quality capped by your hardware','Setup time vs hosted'],
    bestFor:'Privacy-sensitive users, tinkerers, on-device builders',
    alternatives:['huggingface','openrouter','vercel-ai'] },

  /* ============= AGENTS & FRAMEWORKS ============= */
  { slug:'manus', name:'Manus', maker:'Monica', cat:'agents', tier:'frontier',
    pricing:'Free · $39/mo · $199/mo', url:'https://manus.im',
    blurb:'General-purpose autonomous agent that actually delivers.',
    summary:'Manus runs long, multi-step tasks in its own browser-and-shell environment — research dossiers, market scans, content pipelines, even simple apps. The breakout consumer agent of 2025, now with a refined task viewer and credit-based pricing.',
    strengths:['Genuinely autonomous, not just multi-step prompting','Transparent task replay','Strong at research and content workflows'],
    weaknesses:['Credits burn fast on heavy tasks','Reliability varies on novel domains'],
    bestFor:'Solo founders, analysts, marketers',
    alternatives:['chatgpt','genspark','perplexity'] },

  { slug:'devin', name:'Devin', maker:'Cognition', cat:'agents', tier:'frontier',
    pricing:'$20/mo · ACU-based · Team plans', url:'https://devin.ai',
    blurb:'Autonomous software engineer. Files PRs, fixes bugs, takes Slack tickets.',
    summary:'Cognition’s Devin is an asynchronous coding agent that lives in Slack, GitHub, and Linear. You give it a ticket; it spins up a sandbox, writes code, runs tests, and opens a PR. Best on well-scoped maintenance and migration work.',
    strengths:['Async — works while you don’t','Tight Slack / Linear / GitHub integration','Good at scoped maintenance tasks'],
    weaknesses:['Burns Agent Compute Units fast','Greenfield product work still needs supervision'],
    bestFor:'Engineering teams with backlog of small tickets',
    alternatives:['claude-code','cursor','codex'] },

  { slug:'claude-code', name:'Claude Code', maker:'Anthropic', cat:'coding', tier:'frontier',
    pricing:'Bundled with Claude Pro / Max · API', url:'https://www.claude.com/product/claude-code',
    blurb:'Terminal-native coding agent powered by Opus 4.7. The senior pair-programmer.',
    summary:'Claude Code runs in your terminal and now in IDEs and on the web — it plans, edits across many files, runs tests, reads logs, and ships. With Opus 4.7 leading SWE-bench Verified, it has become the default choice for engineers doing real work in production codebases.',
    strengths:['80%+ on SWE-bench Verified','First-class plan / edit / test loop','Hooks, slash commands, MCP, sub-agents','Terminal, IDE, and web entry points'],
    weaknesses:['Token-hungry on large repos','Best results require thoughtful prompts and CLAUDE.md'],
    bestFor:'Engineers who live in the terminal',
    alternatives:['cursor','codex','windsurf'] },

  { slug:'openai-agent', name:'ChatGPT Agent', maker:'OpenAI', cat:'agents', tier:'leading',
    pricing:'Plus · Pro · Enterprise', url:'https://operator.chatgpt.com',
    blurb:'Browser-using agent inside ChatGPT. Books, buys, fills forms.',
    summary:'OpenAI’s agent lineage — Operator and the newer ChatGPT Agent — gives ChatGPT its own browser and filesystem to take real actions: research, scheduling, purchases, form-filling. Strong at well-bounded web tasks; ask before letting it spend money.',
    strengths:['Real browser actions','Built into ChatGPT','Handles checkout and form flows'],
    weaknesses:['Slow on complex tasks','Authentication frictions on locked sites'],
    bestFor:'ChatGPT users who want hands-off web tasks',
    alternatives:['manus','perplexity-assistant','genspark'] },

  { slug:'perplexity-assistant', name:'Perplexity Comet & Assistant', maker:'Perplexity', cat:'agents', tier:'leading',
    pricing:'Free · $20/mo · $200 Max', url:'https://www.perplexity.ai/comet',
    blurb:'Action-taking research agent — and a browser of its own.',
    summary:'Perplexity’s Assistant runs in Comet (its agentic browser) and in the iOS / Android apps — answering with citations and then taking the next step: booking, replying to email, summarising tabs. The cleanest blend of search and action.',
    strengths:['Cited answers, then acts on them','Comet browser is genuinely good','Available on web, mobile, desktop'],
    weaknesses:['Comet still maturing','Heavy use needs Pro / Max'],
    bestFor:'Research-heavy knowledge workers',
    alternatives:['perplexity','chatgpt','manus'] },

  { slug:'genspark', name:'Genspark Super Agent', maker:'Genspark', cat:'agents', tier:'leading',
    pricing:'Free credits · $24.99/mo', url:'https://www.genspark.ai',
    blurb:'AI phone calls, slide decks, and multimedia output in one agent.',
    summary:'Genspark’s Super Agent stitches together LLMs, voice agents, image and video models, and a phone-call layer to ship real artefacts — slide decks, marketing assets, even live restaurant bookings via voice.',
    strengths:['Bundled multimedia output','AI phone calls that actually work','Generous free credits'],
    weaknesses:['Quality is a remix of underlying models','Less control than building yourself'],
    bestFor:'Solo operators, marketers, agencies',
    alternatives:['manus','chatgpt','gamma'] },

  { slug:'lindy', name:'Lindy', maker:'Lindy', cat:'agents', tier:'specialist',
    pricing:'Free · $49.99/mo+', url:'https://www.lindy.ai',
    blurb:'Business automation agents — meeting notes, inboxes, CRM hygiene.',
    summary:'Lindy lets non-engineers compose business agents — email triage, meeting recaps, CRM updates, recruiting outreach — with triggers, templates, and a marketplace of pre-built Lindies.',
    strengths:['No-code agent builder','Big template library','Connects to Gmail, Slack, HubSpot, etc.'],
    weaknesses:['Less powerful than custom code on complex flows'],
    bestFor:'Ops, sales, recruiting teams',
    alternatives:['zapier','n8n','relevance-ai'] },

  { slug:'crewai', name:'CrewAI', maker:'CrewAI', cat:'agents', tier:'specialist',
    pricing:'Open-source · Enterprise plans', url:'https://www.crewai.com',
    blurb:'Multi-agent orchestration — give roles to LLMs and let them collaborate.',
    summary:'CrewAI is a Python framework for building “crews” of role-based agents that plan, delegate, and execute together. Pairs with a managed enterprise platform for deployment, observability, and human-in-the-loop review.',
    strengths:['Clean role / task / crew abstraction','Battle-tested in production','Both OSS and managed tiers'],
    weaknesses:['Python-only','Multi-agent loops can get expensive'],
    bestFor:'Developers building multi-step business agents',
    alternatives:['langgraph','langchain','autogpt'] },

  { slug:'langchain', name:'LangChain', maker:'LangChain', cat:'agents', tier:'leading',
    pricing:'Open-source · LangSmith from $0', url:'https://www.langchain.com',
    blurb:'The dominant LLM application framework — chains, tools, RAG, the works.',
    summary:'LangChain is the most widely used framework for composing LLM applications: prompts, retrievers, tools, memory. The team also ships LangGraph (stateful agents), LangSmith (tracing and evals), and the LangChain Academy. The default starting point for serious LLM engineering.',
    strengths:['Largest community and integration list','First-class Python and JS','LangSmith observability is excellent'],
    weaknesses:['Surface area can feel sprawling','Versions move fast'],
    bestFor:'Engineers building LLM apps in production',
    alternatives:['langgraph','llamaindex','vercel-ai'] },

  { slug:'langgraph', name:'LangGraph', maker:'LangChain', cat:'agents', tier:'open',
    pricing:'Open-source · LangGraph Platform', url:'https://www.langchain.com/langgraph',
    blurb:'Stateful, controllable agent runtime — graphs of LLM steps.',
    summary:'LangGraph is LangChain’s low-level agent framework: explicit state machines, durable execution, human-in-the-loop, and time-travel debugging. The Platform tier handles deployment and persistence.',
    strengths:['Explicit, debuggable agent graphs','Durable execution','Pairs with LangSmith for tracing'],
    weaknesses:['Steeper learning curve than chains','Mostly Python-first'],
    bestFor:'Teams building reliable, long-running agents',
    alternatives:['langchain','crewai','autogpt'] },

  { slug:'autogpt', name:'AutoGPT', maker:'Significant Gravitas', cat:'agents', tier:'open',
    pricing:'Free · self-host', url:'https://agpt.co',
    blurb:'The original autonomous agent. Now a no-code platform for building them.',
    summary:'AutoGPT pioneered the autonomous-agent loop and has since evolved into a self-hostable, no-code platform with a visual builder, marketplace of agents, and cloud edition. A useful playground for the agent-curious.',
    strengths:['Visual agent builder','Marketplace of pre-built blocks','Free to self-host'],
    weaknesses:['Reliability still a research problem','Less production-grade than CrewAI / LangGraph'],
    bestFor:'Hobbyists and agent researchers',
    alternatives:['crewai','langgraph','n8n'] },

  /* ============= IMAGE GENERATION ============= */
  { slug:'midjourney', name:'Midjourney', maker:'Midjourney', cat:'image', tier:'frontier',
    pricing:'$10 / $30 / $60 / $120 per month', url:'https://www.midjourney.com',
    blurb:'Best artistic and cinematic style. The aesthetic standard.',
    summary:'Midjourney v7 still sets the bar for cinematic, painterly, and editorial imagery. The web app brings boards, mood control, and the new omni-reference and personalisation features that lock down a consistent style.',
    strengths:['Unmatched aesthetic out-of-the-box','Personalisation and style references','Active, knowledgeable community'],
    weaknesses:['Photoreal less strong than FLUX','Discord legacy still leaks through'],
    bestFor:'Designers, art directors, illustrators',
    alternatives:['flux','imagen','leonardo'] },

  { slug:'flux', name:'FLUX 1.1 Pro', maker:'Black Forest Labs', cat:'image', tier:'frontier',
    pricing:'API from $0.05 / image · Pro hosted', url:'https://blackforestlabs.ai',
    blurb:'Best-in-class photorealism with sharp text. The pros’ default.',
    summary:'Black Forest Labs’ FLUX family — Pro, Dev, Schnell, and the new Kontext editor — leads on photorealism and text-in-image, and is the engine behind many other apps (Mistral, Krea, Freepik). Available via API and partner platforms.',
    strengths:['Best photoreal in the open / API space','FLUX Kontext for prompt-based editing','Open Schnell + Dev tiers'],
    weaknesses:['No first-party consumer app','Less stylised than Midjourney by default'],
    bestFor:'Builders, photographers, ad creatives',
    alternatives:['midjourney','imagen','recraft'] },

  { slug:'imagen', name:'Imagen 4', maker:'Google DeepMind', cat:'image', tier:'frontier',
    pricing:'Bundled in Gemini · Vertex AI API', url:'https://deepmind.google/technologies/imagen/',
    blurb:'Best prompt adherence and text rendering at frontier scale.',
    summary:'Google’s Imagen 4 is the most prompt-faithful frontier model — it follows complex compositions and renders text reliably. Available inside Gemini, Whisk, and the Vertex AI API.',
    strengths:['Excellent prompt adherence','Crisp text in images','Tight Google product integration'],
    weaknesses:['Style range narrower than Midjourney','API-first; consumer UX is fragmented'],
    bestFor:'Workspace users, ad and marketing teams',
    alternatives:['flux','midjourney','dalle'] },

  { slug:'dalle', name:'DALL·E / GPT Image', maker:'OpenAI', cat:'image', tier:'leading',
    pricing:'Bundled with ChatGPT', url:'https://openai.com/index/dall-e-3/',
    blurb:'The image model built into ChatGPT. Good enough for most.',
    summary:'OpenAI’s GPT-Image (the successor to DALL·E 3) is built directly into ChatGPT. Good prompt adherence, in-painting, and the ability to iterate inside a conversation make it the easiest first stop for most non-pros.',
    strengths:['Inside ChatGPT — zero extra friction','In-conversation iteration','Decent text rendering'],
    weaknesses:['Style ceiling below Midjourney','Limited fine control'],
    bestFor:'Casual creators, ChatGPT users',
    alternatives:['midjourney','flux','imagen'] },

  { slug:'ideogram', name:'Ideogram 3.0', maker:'Ideogram', cat:'image', tier:'leading',
    pricing:'Free · $7/mo · $16/mo · $48/mo', url:'https://ideogram.ai',
    blurb:'Best for posters, logos, and any image with serious text.',
    summary:'Ideogram 3.0 specialises in typography and graphic design — posters, mockups, packaging, logos. Magic Prompt and Style References make it a quietly powerful tool for designers who need text that actually reads.',
    strengths:['Best-in-class text rendering','Style references','Generous free tier'],
    weaknesses:['Less general-purpose photoreal','Smaller community than Midjourney'],
    bestFor:'Graphic designers, marketers',
    alternatives:['midjourney','recraft','canva'] },

  { slug:'firefly', name:'Adobe Firefly', maker:'Adobe', cat:'image', tier:'leading',
    pricing:'Bundled with Creative Cloud · standalone $9.99', url:'https://firefly.adobe.com',
    blurb:'IP-safe, Creative Cloud-native generative imagery.',
    summary:'Firefly is Adobe’s commercially-safe image, video, and audio model — trained on licensed content, baked into Photoshop, Illustrator, and Premiere as Generative Fill, Generate Image, Generate Video, and more.',
    strengths:['Commercially safe outputs','Inside Photoshop, Illustrator, Premiere','Good Generative Fill'],
    weaknesses:['Raw quality lags Midjourney / FLUX','Best with a Creative Cloud subscription'],
    bestFor:'Working designers in Adobe apps',
    alternatives:['canva','midjourney','recraft'] },

  { slug:'leonardo', name:'Leonardo.Ai', maker:'Leonardo (Canva)', cat:'image', tier:'specialist',
    pricing:'Free · $12/mo · $30/mo · $60/mo', url:'https://leonardo.ai',
    blurb:'Game-asset and concept-art workflows with serious control.',
    summary:'Leonardo (now part of Canva) is built for concept art, game assets, and brand work — model fine-tuning, Canvas editor, real-time generation, image-to-3D, and a deep prompt library. The choice for production creatives who need control beyond a single prompt.',
    strengths:['Custom model training','Real-time canvas','Strong control net features','Image-to-3D'],
    weaknesses:['Interface can feel busy','Pricing tiers stack up'],
    bestFor:'Game studios, concept artists, brand teams',
    alternatives:['midjourney','recraft','krea'] },

  { slug:'recraft', name:'Recraft', maker:'Recraft', cat:'image', tier:'specialist',
    pricing:'Free · $12/mo · $33/mo · $99/mo', url:'https://www.recraft.ai',
    blurb:'Vector-native AI for brand, icon, and illustration work.',
    summary:'Recraft is the only frontier model with first-class SVG / vector output — perfect for icons, logos, and brand systems. Style controls, brand-style locking, and real raster too. A favourite of designers building actual systems, not one-offs.',
    strengths:['Native SVG output','Brand-style locking','Best icon and illustration model'],
    weaknesses:['Less general-purpose than FLUX','Vector quality requires careful prompts'],
    bestFor:'Brand designers, icon makers, illustrators',
    alternatives:['ideogram','midjourney','figma-make'] },

  { slug:'krea', name:'Krea', maker:'Krea', cat:'image', tier:'specialist',
    pricing:'Free · $10/mo · $35/mo · $60/mo', url:'https://www.krea.ai',
    blurb:'Real-time generation, enhancement, and a creative playground.',
    summary:'Krea wraps the best image and video models (FLUX, Imagen, Veo, Kling, and others) in a real-time canvas with enhancement, in-painting, training, and the Krea Realtime model. The fastest “mess around” tool in the space.',
    strengths:['Real-time canvas','Multiple model providers in one UI','Enhancement and upscaling'],
    weaknesses:['Per-feature credit costs','Best on a fast machine'],
    bestFor:'Designers, motion creatives, prototypers',
    alternatives:['leonardo','runway','fal'] },

  { slug:'sdxl', name:'Stable Diffusion / SDXL', maker:'Stability AI', cat:'image', tier:'open',
    pricing:'Free · self-host', url:'https://stability.ai',
    blurb:'Open-weights image generation. Self-host for full control.',
    summary:'The Stable Diffusion lineage — SDXL, SD3, and the newer Stable Image Ultra — remains the open-weight backbone of the image-gen world. Pair with ComfyUI or Automatic1111 for total control.',
    strengths:['Open weights','Massive ecosystem of LoRAs and ControlNets','No vendor lock-in'],
    weaknesses:['Setup takes work','Quality below frontier closed models'],
    bestFor:'Self-hosters, ML engineers, researchers',
    alternatives:['comfyui','flux','huggingface'] },

  { slug:'comfyui', name:'ComfyUI', maker:'Comfy Org', cat:'image', tier:'open',
    pricing:'Free · self-host · cloud tiers', url:'https://www.comfy.org',
    blurb:'Node-based UI for image, video, and audio model pipelines.',
    summary:'ComfyUI is the pro’s playground — a graph-based workflow builder for stitching together image, video, and audio models with surgical control. The standard for power users who outgrew one-prompt UIs.',
    strengths:['Total control via node graphs','Huge custom-node ecosystem','Runs nearly any open model'],
    weaknesses:['Steep learning curve','You’re your own infra team'],
    bestFor:'Power users, VFX, generative pipelines',
    alternatives:['sdxl','flux','fal'] },

  /* ============= VIDEO ============= */
  { slug:'veo', name:'Veo 3.1', maker:'Google DeepMind', cat:'video', tier:'frontier',
    pricing:'Bundled in Gemini · Vertex AI · Flow', url:'https://deepmind.google/technologies/veo/',
    blurb:'4K video with native synced audio. The Sora replacement.',
    summary:'Veo 3.1 generates 1080p and 4K video with native synced dialogue and ambient audio in a single pass. Available inside Gemini, the Flow filmmaking app, and Vertex AI. Currently the most coherent video model on serious physics and faces.',
    strengths:['Native synced audio','Strong physics and motion','Inside Gemini and Vertex'],
    weaknesses:['Strict content filters','Generation is slow and expensive'],
    bestFor:'Ad creatives, filmmakers, prototypers',
    alternatives:['runway','kling','luma'] },

  { slug:'runway', name:'Runway Gen-4', maker:'Runway', cat:'video', tier:'frontier',
    pricing:'Free · $15/mo · $35/mo · $95/mo', url:'https://runwayml.com',
    blurb:'Best creative control. Motion Brush, references, full editor.',
    summary:'Runway is the studio that has stayed ahead on creative control — Gen-4 video, Act-Two motion capture, References, Brushes, and a full editor. The choice when you need direction, not just generation.',
    strengths:['Most controllable creative tool','Reference-based consistency','Full editor and timeline'],
    weaknesses:['Quality ceiling slightly below Veo','Pricing tiers add up'],
    bestFor:'Filmmakers, motion designers, agencies',
    alternatives:['veo','kling','luma'] },

  { slug:'sora', name:'Sora 2', maker:'OpenAI', cat:'video', tier:'leading',
    pricing:'ChatGPT Plus / Pro · Sora app', url:'https://sora.com',
    blurb:'OpenAI’s video model with synced audio and a TikTok-style app.',
    summary:'Sora 2 added native sound and a standalone consumer app where the feed is generated. Strong at stylised scenes; the social product is a separate experiment from the underlying model.',
    strengths:['Native audio','Standalone app','Tight ChatGPT integration'],
    weaknesses:['Hard physics still trips it up','Heavy moderation'],
    bestFor:'ChatGPT subscribers, social creators',
    alternatives:['veo','runway','pika'] },

  { slug:'kling', name:'Kling 2', maker:'Kuaishou', cat:'video', tier:'leading',
    pricing:'Free credits · subscriptions from $10/mo', url:'https://klingai.com',
    blurb:'Long clips, 4K, lip-sync, and motion brushes. The dark horse.',
    summary:'Kuaishou’s Kling has matured into a serious frontier video tool — multi-shot generation, 4K, lip-sync, motion control, and effects. Often the best price-to-quality ratio in the category.',
    strengths:['Long-clip support','Lip-sync and motion control','Aggressive pricing'],
    weaknesses:['China-hosted; latency varies','Less editor polish than Runway'],
    bestFor:'Creators who need length and budget control',
    alternatives:['veo','runway','luma'] },

  { slug:'luma', name:'Luma Dream Machine / Ray3', maker:'Luma', cat:'video', tier:'leading',
    pricing:'Free · $9.99 / $29.99 / $94.99 per month', url:'https://lumalabs.ai/dream-machine',
    blurb:'4K HDR with strong physics reasoning. Camera and concepts.',
    summary:'Luma’s Ray3 model brings 4K HDR, draft mode, camera concepts, and strong physics. Dream Machine’s Boards UI is one of the calmest creative environments in AI video.',
    strengths:['4K HDR output','Draft mode for fast iteration','Excellent camera control'],
    weaknesses:['Long-form coherence still tricky','Smaller community than Runway'],
    bestFor:'Stylised storytellers, motion designers',
    alternatives:['runway','veo','kling'] },

  { slug:'pika', name:'Pika', maker:'Pika', cat:'video', tier:'leading',
    pricing:'Free · $10/mo · $35/mo · $70/mo', url:'https://pika.art',
    blurb:'Fast renders, Pikaffects, and the most fun social video toolkit.',
    summary:'Pika leans into delight — Pikaffects, Pikascenes, character ingestion, and a steady drip of meme-able creative templates. Faster than the heavyweights when you just need a clip.',
    strengths:['Fast generation','Inventive creative effects','Friendly UX'],
    weaknesses:['Quality below Veo / Runway top-end','Less editorial control'],
    bestFor:'Social creators, marketers',
    alternatives:['runway','luma','sora'] },

  { slug:'higgsfield', name:'Higgsfield', maker:'Higgsfield', cat:'video', tier:'specialist',
    pricing:'Free credits · $9 / $29 / $49 per month', url:'https://higgsfield.ai',
    blurb:'Cinematic camera control and identity-locked AI video.',
    summary:'Higgsfield specialises in cinematic camera moves and identity-locked characters — bullet-time, dolly zooms, character reference, and a fast-growing library of motion presets. The choice when you want the shot, not just the scene.',
    strengths:['Cinematic camera presets','Identity / character lock','Mobile-friendly creator tools'],
    weaknesses:['Narrower than the all-rounders','Best on social-format clips'],
    bestFor:'Short-form storytellers, social filmmakers',
    alternatives:['runway','kling','luma'] },

  { slug:'heygen', name:'HeyGen', maker:'HeyGen', cat:'video', tier:'specialist',
    pricing:'Free · $24/mo · $72/mo · enterprise', url:'https://www.heygen.com',
    blurb:'AI avatars, dubbing, and translation for business video.',
    summary:'HeyGen turns scripts into talking-head video with avatars, voice clones, and instant translation across 175+ languages. The default for L&D, sales outreach, and localised marketing video.',
    strengths:['Realistic AI avatars','Real-time translation and dubbing','API and Zapier integration'],
    weaknesses:['Avatars still betray themselves at length','Not for cinematic work'],
    bestFor:'Sales, training, localisation teams',
    alternatives:['elevenlabs','runway','wan'] },

  { slug:'wan', name:'Wan 2', maker:'Alibaba', cat:'video', tier:'open',
    pricing:'Free · open weights', url:'https://wan.video',
    blurb:'Open-weights video generation. Self-host or play in the studio.',
    summary:'Alibaba’s Wan family is the leading open-weights video model — image-to-video, video-to-video, audio-driven, and a free hosted studio for casual use. The serious self-host option.',
    strengths:['Open weights','Image-to-video and audio-driven modes','Free hosted studio'],
    weaknesses:['Quality behind frontier closed models','Hardware-hungry to self-host'],
    bestFor:'Researchers, self-hosters, OSS-first teams',
    alternatives:['comfyui','runway','kling'] },

  /* ============= MUSIC & AUDIO ============= */
  { slug:'suno', name:'Suno', maker:'Suno', cat:'music', tier:'frontier',
    pricing:'Free · $10/mo · $30/mo · $200 enterprise', url:'https://suno.com',
    blurb:'Complete songs with vocals. Plus a Studio DAW for serious work.',
    summary:'Suno v5 produces full songs — lyrics, vocals, instrumentation — at a quality non-musicians can’t distinguish from a real release. Suno Studio adds stems, layering, and a real DAW for producers.',
    strengths:['Complete songs from a prompt','Studio DAW with stems','Voice cloning and personas'],
    weaknesses:['Licensing of training data is contested','Mix quality varies by genre'],
    bestFor:'Songwriters, podcasters, content creators',
    alternatives:['udio','elevenlabs-music','aiva'] },

  { slug:'udio', name:'Udio', maker:'Udio', cat:'music', tier:'leading',
    pricing:'Free · $10/mo · $30/mo', url:'https://www.udio.com',
    blurb:'Audiophile-grade generation with serious editing tools.',
    summary:'Udio sits next to Suno as the other top music model — known for cleaner mixes, in-painting, stem separation, and a deeper editing surface. The producer’s pick of the two.',
    strengths:['Cleaner production by default','In-painting and stems','Strong genre coverage'],
    weaknesses:['Smaller mobile presence','Library not as deep as Suno’s'],
    bestFor:'Producers, sound designers',
    alternatives:['suno','aiva','elevenlabs-music'] },

  { slug:'elevenlabs-music', name:'ElevenLabs Music', maker:'ElevenLabs', cat:'music', tier:'leading',
    pricing:'Bundled with ElevenLabs plans', url:'https://elevenlabs.io/music',
    blurb:'Licensed-data music model with the best vocal realism.',
    summary:'ElevenLabs Music is trained on licensed catalogues — a big deal for commercial use. Vocals inherit ElevenLabs’ industry-leading TTS quality, and outputs come with stems.',
    strengths:['Licensed training data','World-class vocal realism','Stems included'],
    weaknesses:['Newer model — fewer presets than Suno','Tied to ElevenLabs subscription'],
    bestFor:'Brands and agencies that need clean licensing',
    alternatives:['suno','udio','aiva'] },

  { slug:'aiva', name:'AIVA', maker:'AIVA', cat:'music', tier:'specialist',
    pricing:'Free · €11/mo · €33/mo', url:'https://www.aiva.ai',
    blurb:'Orchestral and cinematic composition with proper notation.',
    summary:'AIVA is the long-running specialist for cinematic, orchestral, and game-score music. Editable MIDI, proper score export, and copyright ownership at the Pro tier.',
    strengths:['Proper MIDI / score editing','Cinematic genre depth','Copyright ownership at Pro'],
    weaknesses:['Less impressive on vocal pop','Niche compared with Suno / Udio'],
    bestFor:'Composers, game and film teams',
    alternatives:['suno','udio','lyria'] },

  { slug:'lyria', name:'Lyria RealTime', maker:'Google DeepMind', cat:'music', tier:'specialist',
    pricing:'Vertex AI API · MusicFX in Labs', url:'https://deepmind.google/technologies/lyria/',
    blurb:'Adaptive, real-time music generation for games and live media.',
    summary:'Google’s Lyria 2 / RealTime focuses on continuous, controllable music generation — perfect for games, live experiences, and adaptive scoring. Available via Vertex and the MusicFX experiments.',
    strengths:['Real-time, adaptive music','Tight Google API integration','Strong loop and stem control'],
    weaknesses:['No mainstream consumer app','Best inside builds, not browsers'],
    bestFor:'Game studios, interactive media',
    alternatives:['suno','aiva','stable-audio'] },

  { slug:'stable-audio', name:'Stable Audio', maker:'Stability AI', cat:'music', tier:'open',
    pricing:'Free · $11.99/mo · $29.99/mo', url:'https://stableaudio.com',
    blurb:'Open-weights audio generation for samples, FX, and loops.',
    summary:'Stable Audio 2 generates up to three minutes of sound — music, effects, ambience, and stems. Open weights make it the go-to for game and app studios who need to host on their own infra.',
    strengths:['Open-weights option','Sample / FX / loop focus','Stems included'],
    weaknesses:['Pop song quality below Suno','Less vocal-friendly'],
    bestFor:'Sound designers, game studios',
    alternatives:['suno','elevenlabs-music','aiva'] },

  /* ============= VOICE & SPEECH ============= */
  { slug:'elevenlabs', name:'ElevenLabs', maker:'ElevenLabs', cat:'voice', tier:'frontier',
    pricing:'Free · $5 / $22 / $99 per month', url:'https://elevenlabs.io',
    blurb:'Best TTS, voice cloning, and dubbing — by a clear margin.',
    summary:'ElevenLabs leads on text-to-speech, voice cloning, dubbing in 70+ languages, and now real-time conversational voice agents and a full Studio for long-form audio. The default audio engine for podcasts, audiobooks, and product UX.',
    strengths:['World-class voice quality','Cloning in seconds','Dubbing across 70+ languages','Conversational voice agents'],
    weaknesses:['Cloning ethics need care','Bills run up at scale'],
    bestFor:'Podcasters, audiobook producers, product teams',
    alternatives:['openai-voice','hume','cartesia'] },

  { slug:'openai-voice', name:'OpenAI Voice', maker:'OpenAI', cat:'voice', tier:'leading',
    pricing:'Bundled in ChatGPT · Realtime API', url:'https://openai.com/index/introducing-the-realtime-api/',
    blurb:'Real-time conversational voice. The most natural latency in the space.',
    summary:'OpenAI’s Realtime API and ChatGPT Voice Mode deliver low-latency, interruptible spoken conversation with the underlying model. The benchmark for any “talk to an AI” product.',
    strengths:['Natural turn-taking and interruption','Inside ChatGPT for free users','Realtime API for builders'],
    weaknesses:['Voice library smaller than ElevenLabs','Tied to OpenAI ecosystem'],
    bestFor:'ChatGPT users, voice-product builders',
    alternatives:['elevenlabs','hume','cartesia'] },

  { slug:'hume', name:'Hume AI', maker:'Hume', cat:'voice', tier:'specialist',
    pricing:'Free · usage-based API', url:'https://www.hume.ai',
    blurb:'Emotionally expressive voice with prosody you can steer.',
    summary:'Hume’s EVI (Empathic Voice Interface) and Octave TTS focus on the emotional layer of speech — tone, pacing, expressiveness — giving voice agents real bedside manner.',
    strengths:['Best-in-class expressive voice','Emotion-aware turn-taking','Open developer SDKs'],
    weaknesses:['Smaller voice catalogue','Niche relative to ElevenLabs'],
    bestFor:'Mental-health, coaching, character AI',
    alternatives:['elevenlabs','cartesia','openai-voice'] },

  { slug:'cartesia', name:'Cartesia Sonic', maker:'Cartesia', cat:'voice', tier:'specialist',
    pricing:'Free · usage-based API', url:'https://cartesia.ai',
    blurb:'Lowest-latency real-time voice. Perfect for agents.',
    summary:'Cartesia’s Sonic models deliver sub-100ms voice latency with strong quality — ideal for phone agents, kiosks, and any product where every millisecond matters.',
    strengths:['Lowest end-to-end latency','Strong streaming TTS','Multilingual voices'],
    weaknesses:['Less consumer presence','Voice library smaller than ElevenLabs'],
    bestFor:'Voice-agent and call-centre builders',
    alternatives:['elevenlabs','vapi','openai-voice'] },

  { slug:'resemble', name:'Resemble AI', maker:'Resemble', cat:'voice', tier:'specialist',
    pricing:'Free · $19/mo · $99/mo · enterprise', url:'https://www.resemble.ai',
    blurb:'Voice cloning with emotion control and deepfake detection.',
    summary:'Resemble AI offers voice cloning, real-time speech-to-speech conversion, and a security layer for detecting voice deepfakes. Strong enterprise positioning around safety.',
    strengths:['High-quality cloning','Deepfake detection layer','Speech-to-speech conversion'],
    weaknesses:['UX behind ElevenLabs','Pricing less transparent'],
    bestFor:'Brands managing voice IP, security-conscious teams',
    alternatives:['elevenlabs','hume','cartesia'] },

  { slug:'whisper', name:'Whisper', maker:'OpenAI', cat:'voice', tier:'open',
    pricing:'Free · open weights · API', url:'https://openai.com/index/whisper/',
    blurb:'The default open-weights speech-to-text model.',
    summary:'Whisper is OpenAI’s open-source ASR model — multilingual, robust, and the basis for almost every transcription tool you use. Run it locally or via the API.',
    strengths:['Open weights','Excellent multilingual ASR','Tiny to large variants'],
    weaknesses:['Large models are slow on CPU','Less polished diarisation'],
    bestFor:'Builders adding transcription anywhere',
    alternatives:['huggingface','elevenlabs','openai-voice'] },

  { slug:'vapi', name:'Vapi', maker:'Vapi', cat:'voice', tier:'specialist',
    pricing:'Pay per minute · API', url:'https://vapi.ai',
    blurb:'Build production voice agents in days. The Twilio of AI calls.',
    summary:'Vapi is developer infrastructure for voice agents — telephony, real-time STT/TTS, function-calling, and analytics in one SDK. Powering a generation of AI sales, support, and scheduling agents.',
    strengths:['One SDK for the whole voice stack','Telephony built in','Strong real-time pipelines'],
    weaknesses:['Per-minute pricing adds up','Engineering needed to ship'],
    bestFor:'Builders shipping voice agents to phones',
    alternatives:['bland','cartesia','elevenlabs'] },

  { slug:'bland', name:'Bland AI', maker:'Bland', cat:'voice', tier:'specialist',
    pricing:'$0.09/min and up · enterprise', url:'https://www.bland.ai',
    blurb:'Enterprise-grade phone-call agents at scale.',
    summary:'Bland’s Conversational Pathways and self-hosted infrastructure make it the choice for enterprises running hundreds of thousands of AI calls — sales, support, surveys, scheduling.',
    strengths:['Scales to millions of minutes','Pathway designer for complex flows','Self-host option for compliance'],
    weaknesses:['Enterprise-shaped, not weekend-project shaped'],
    bestFor:'Call-centre, sales, scheduling at scale',
    alternatives:['vapi','cartesia','elevenlabs'] },

  /* ============= CODING & DEVELOPER ============= */
  { slug:'cursor', name:'Cursor', maker:'Anysphere', cat:'coding', tier:'frontier',
    pricing:'Free · $20/mo Pro · $40/mo Ultra · Teams', url:'https://cursor.com',
    blurb:'Best AI-native IDE. Where most professional engineers write code now.',
    summary:'Cursor is the AI-first fork of VS Code that pioneered tab autocomplete, the @-context system, and Composer / Agent for multi-file edits. Backed by frontier models from Anthropic, OpenAI, and Google. The de facto IDE for AI-assisted engineering.',
    strengths:['Best inline autocomplete','Multi-file Agent / Composer','BYO model + enterprise tier'],
    weaknesses:['Subscription on top of model costs','Heavier than plain VS Code'],
    bestFor:'Working software engineers',
    alternatives:['windsurf','claude-code','copilot'] },

  { slug:'copilot', name:'GitHub Copilot', maker:'GitHub', cat:'coding', tier:'leading',
    pricing:'Free · $10/mo · $19/mo Business', url:'https://github.com/features/copilot',
    blurb:'Widest IDE support and the original AI pair-programmer.',
    summary:'GitHub Copilot now covers chat, agent mode, code review, and a coding agent that opens PRs from issues — across VS Code, JetBrains, Visual Studio, Xcode, and the GitHub web. The safe enterprise default.',
    strengths:['Works in every major IDE','GitHub-native PR / review flows','Strong enterprise compliance story'],
    weaknesses:['Behind Cursor / Claude Code on cutting-edge UX','Quality varies by model choice'],
    bestFor:'Enterprise engineering teams',
    alternatives:['cursor','claude-code','windsurf'] },

  { slug:'codex', name:'OpenAI Codex', maker:'OpenAI', cat:'coding', tier:'leading',
    pricing:'Bundled with ChatGPT · API', url:'https://chatgpt.com/codex',
    blurb:'OpenAI’s coding agent across cloud, CLI, and IDE.',
    summary:'The new Codex is OpenAI’s coding agent — runs in the cloud from chatgpt.com/codex, locally as a CLI, and inside ChatGPT’s IDE extensions. Strong at well-scoped feature work and bug fixes.',
    strengths:['Multiple entry points (web, CLI, IDE)','Tight ChatGPT integration','Async cloud sandboxes'],
    weaknesses:['Behind Claude Code on long agentic loops','Heavy ChatGPT lock-in'],
    bestFor:'ChatGPT subscribers, OpenAI shops',
    alternatives:['claude-code','cursor','devin'] },

  { slug:'windsurf', name:'Windsurf', maker:'Cognition', cat:'coding', tier:'leading',
    pricing:'Free · $15/mo Pro · Enterprise', url:'https://windsurf.com',
    blurb:'IDE built around the Cascade agent. Multi-file edits done well.',
    summary:'Windsurf (now under Cognition, who also make Devin) is a VS Code-based IDE with the Cascade agent at its core — multi-file editing, terminal control, and a calm, focused UX.',
    strengths:['Cascade is genuinely good at multi-file edits','Free tier is generous','Clean focused UI'],
    weaknesses:['Smaller community than Cursor','Less aggressive on the bleeding edge'],
    bestFor:'Engineers who want a quieter Cursor',
    alternatives:['cursor','claude-code','copilot'] },

  { slug:'replit', name:'Replit Agent', maker:'Replit', cat:'coding', tier:'specialist',
    pricing:'Free · $25/mo Core · Teams · Enterprise', url:'https://replit.com',
    blurb:'Cloud IDE plus an agent that ships full apps.',
    summary:'Replit Agent 3 builds and deploys full-stack apps end-to-end inside a cloud IDE — frontends, backends, databases, auth, payments. The fastest way to go from idea to a live URL without leaving the browser.',
    strengths:['Cloud IDE + deploys in one','Database, auth, secrets included','Generous free tier'],
    weaknesses:['Cloud-only','Real production work eventually outgrows it'],
    bestFor:'PMs, designers, weekend-project hackers',
    alternatives:['v0','lovable','bolt'] },

  { slug:'v0', name:'v0', maker:'Vercel', cat:'coding', tier:'specialist',
    pricing:'Free · $20/mo · $30/mo Team', url:'https://v0.app',
    blurb:'Prompt-to-UI for Next.js, shadcn/ui, and Tailwind.',
    summary:'Vercel’s v0 generates polished React + Tailwind + shadcn/ui components and full apps from natural language. Ships straight to a Vercel deploy. The cleanest path from idea to production-shaped UI.',
    strengths:['Beautiful default components','Direct Vercel deploys','Tight Next.js integration'],
    weaknesses:['Best for React + Tailwind only','Backend depth limited'],
    bestFor:'Designers, frontend engineers, indie hackers',
    alternatives:['lovable','bolt','stitch'] },

  { slug:'lovable', name:'Lovable', maker:'Lovable', cat:'coding', tier:'specialist',
    pricing:'Free · $25/mo · $50/mo · $100/mo', url:'https://lovable.dev',
    blurb:'Full-stack app builder. Idea to working product in an evening.',
    summary:'Lovable turns prompts into full-stack apps with React frontends and Supabase backends — auth, databases, payments, the lot. Visual editing layered on top of real code you can export.',
    strengths:['Real full-stack apps from prompts','Supabase / Stripe / GitHub integration','Visual editor on real code'],
    weaknesses:['Complex apps still need a developer','Credits-based pricing'],
    bestFor:'Founders prototyping real products',
    alternatives:['bolt','v0','replit'] },

  { slug:'bolt', name:'Bolt.new', maker:'StackBlitz', cat:'coding', tier:'specialist',
    pricing:'Free · $20/mo Pro · Teams', url:'https://bolt.new',
    blurb:'In-browser, full-stack development with an agent at the wheel.',
    summary:'Bolt.new runs Node, npm, and your dev server inside the browser via WebContainers, with an agent that scaffolds, edits, and debugs. Pairs naturally with Netlify, Supabase, and Expo for mobile.',
    strengths:['Real Node runtime in the browser','Mobile builds via Expo','One-click Netlify deploys'],
    weaknesses:['Browser tabs aren’t free RAM','Best for web stacks'],
    bestFor:'Indie devs, prototypers',
    alternatives:['v0','lovable','replit'] },

  { slug:'aider', name:'Aider', maker:'Paul Gauthier', cat:'coding', tier:'open',
    pricing:'Free · open-source · BYO API key', url:'https://aider.chat',
    blurb:'Open-source terminal pair-programmer with git baked in.',
    summary:'Aider is a beloved open-source CLI that pairs with any frontier model to edit your repo, run tests, and commit changes. Auto-commits per change make undo trivial.',
    strengths:['Open-source','Per-edit git commits','Works with any major API'],
    weaknesses:['CLI-only','Less polish than Claude Code'],
    bestFor:'OSS-leaning developers',
    alternatives:['claude-code','cline','codex'] },

  { slug:'cline', name:'Cline', maker:'Cline', cat:'coding', tier:'open',
    pricing:'Free open-source · BYO API key', url:'https://cline.bot',
    blurb:'Open-source coding agent inside VS Code. BYO model.',
    summary:'Cline is an open-source autonomous coding agent that lives in VS Code — plans, edits files, runs commands with your approval, and works with any provider (Anthropic, OpenAI, OpenRouter, local models). The OSS counterpart to Cursor’s Composer.',
    strengths:['Open-source','Provider-agnostic','Strong plan / act loop'],
    weaknesses:['You wear API costs directly','Setup takes a minute'],
    bestFor:'OSS-leaning VS Code users',
    alternatives:['cursor','claude-code','aider'] },

  { slug:'stitch', name:'Google Stitch', maker:'Google Labs', cat:'coding', tier:'specialist',
    pricing:'Free during Labs', url:'https://stitch.withgoogle.com',
    blurb:'Prompt-to-UI from Google. Generates designs and front-end code.',
    summary:'Stitch is Google Labs’ AI design-and-code tool — describe an app, get UI mockups and the front-end code to ship. Built on Gemini, with Figma export and iterative design conversations.',
    strengths:['Free while in Labs','Figma export','Conversation-driven iteration'],
    weaknesses:['Front-end only','Labs status — features can change'],
    bestFor:'Designers prototyping app UI',
    alternatives:['v0','figma-make','uizard'] },

  /* ============= SEARCH & RESEARCH ============= */
  { slug:'perplexity', name:'Perplexity', maker:'Perplexity', cat:'search', tier:'frontier',
    pricing:'Free · $20/mo Pro · $200/mo Max', url:'https://www.perplexity.ai',
    blurb:'The AI answer engine standard. Cited, current, fast.',
    summary:'Perplexity is the cleanest answer engine on the market — every claim cited, current information, multiple frontier models behind a single Pro Search. Pro Search and Deep Research handle multi-step queries; Comet brings it into a full browser.',
    strengths:['Always-cited answers','Frontier model choice','Comet browser and Spaces'],
    weaknesses:['Less freeform than ChatGPT for creative tasks'],
    bestFor:'Knowledge workers, researchers, journalists',
    alternatives:['chatgpt','gemini','exa'] },

  { slug:'chatgpt-search', name:'ChatGPT Search & Atlas', maker:'OpenAI', cat:'search', tier:'leading',
    pricing:'Free in ChatGPT · $20/mo Plus', url:'https://chatgpt.com/search',
    blurb:'Real-time search and an AI browser, both inside ChatGPT.',
    summary:'ChatGPT Search brings web answers with citations into the main ChatGPT interface, and the new Atlas browser turns the chat sidebar into a full agentic browser.',
    strengths:['Inside ChatGPT — no second tool','Atlas brings agent-grade browsing','Citations in answers'],
    weaknesses:['Less rigorous citation UX than Perplexity','Atlas still maturing'],
    bestFor:'ChatGPT users who want answers + action',
    alternatives:['perplexity','gemini','grok'] },

  { slug:'notebooklm', name:'NotebookLM', maker:'Google', cat:'search', tier:'specialist',
    pricing:'Free · Plus inside AI Pro', url:'https://notebooklm.google.com',
    blurb:'Grounded research and audio overviews from your own sources.',
    summary:'NotebookLM lets you upload PDFs, slides, web links, and YouTube videos, then ask grounded questions and generate Audio Overviews — the viral “two-host podcast” about your own material.',
    strengths:['Strictly grounded in your sources','Audio Overview podcasts','Mind maps and timelines'],
    weaknesses:['Source size caps on free tier','Best for research, not freeform chat'],
    bestFor:'Students, analysts, anyone with a stack of PDFs',
    alternatives:['kimi','elicit','claude'] },

  { slug:'elicit', name:'Elicit', maker:'Elicit', cat:'search', tier:'specialist',
    pricing:'Free · $14/mo Plus · Pro · Teams', url:'https://elicit.com',
    blurb:'Academic literature review, automated.',
    summary:'Elicit is the research assistant for academia — search across 200M+ papers, extract structured data tables across studies, summarise abstracts, and find supporting / opposing evidence.',
    strengths:['Built for academic literature','Structured data extraction','Cited summaries'],
    weaknesses:['Limited outside scientific papers','Pricing aimed at institutions'],
    bestFor:'Researchers, grad students, R&D teams',
    alternatives:['perplexity','notebooklm','exa'] },

  { slug:'exa', name:'Exa', maker:'Exa', cat:'search', tier:'specialist',
    pricing:'Free credits · usage-based API', url:'https://exa.ai',
    blurb:'Neural web search API for agents and developers.',
    summary:'Exa is a web search API designed for LLMs — semantic queries, structured results, and a Websets product for finding lists of entities (companies, papers, people). The grown-up search backend for agents.',
    strengths:['Semantic search built for AI','Websets for list-building','Strong developer ergonomics'],
    weaknesses:['Not a consumer product','Quality depends on prompt phrasing'],
    bestFor:'Builders adding search to LLM apps',
    alternatives:['tavily','perplexity','huggingface'] },

  { slug:'tavily', name:'Tavily', maker:'Tavily', cat:'search', tier:'specialist',
    pricing:'Free 1k/mo · usage-based', url:'https://www.tavily.com',
    blurb:'Search and extract API tuned for AI agents.',
    summary:'Tavily is a hosted search and crawl API used inside agent stacks — answers, raw results, and content extraction in a single call. Often the first thing a LangChain or LangGraph project plugs in.',
    strengths:['Designed for agents','Generous free tier','Easy LangChain / LangGraph integration'],
    weaknesses:['Smaller index than incumbent search engines','API-only'],
    bestFor:'LLM app developers',
    alternatives:['exa','perplexity','langchain'] },

  /* ============= WRITING & PRODUCTIVITY ============= */
  { slug:'notion-ai', name:'Notion AI', maker:'Notion', cat:'writing', tier:'frontier',
    pricing:'$10/mo add-on · bundled in Business', url:'https://www.notion.so/product/ai',
    blurb:'AI inside the workspace. Drafts, summaries, queries on your data.',
    summary:'Notion AI lives inside Notion pages and databases — drafting, summarising, translating, and now answering questions across your entire workspace and connected apps. The most useful AI you barely notice.',
    strengths:['AI exactly where your work already is','Cross-workspace Q&A','Database-aware automations'],
    weaknesses:['Best as an add-on to existing Notion use'],
    bestFor:'Notion-using teams',
    alternatives:['claude','chatgpt','gemini'] },

  { slug:'grammarly', name:'Grammarly', maker:'Grammarly', cat:'writing', tier:'leading',
    pricing:'Free · $12/mo · $15/mo · Business', url:'https://www.grammarly.com',
    blurb:'The writing-polish standard. Now an AI editor across every app.',
    summary:'Grammarly is everywhere you type, and the AI features have caught up — generative drafts, tone rewrites, citation checking, and a desktop assistant that works across browsers and Office.',
    strengths:['Cross-app coverage','Strong tone and style controls','Mature enterprise compliance'],
    weaknesses:['Suggestions can be conservative','Some advanced features behind Business'],
    bestFor:'Anyone who writes for work',
    alternatives:['notion-ai','sudowrite','jasper'] },

  { slug:'jasper', name:'Jasper', maker:'Jasper', cat:'writing', tier:'specialist',
    pricing:'$39 / $59 / Custom per month', url:'https://www.jasper.ai',
    blurb:'Marketing content at scale with brand voice baked in.',
    summary:'Jasper is the marketing-AI suite for brand teams — brand voices, campaign templates, image generation, and analytics. Best for brands producing dozens of assets a week.',
    strengths:['Brand voice training','Campaign-level workflows','Marketing-focused integrations'],
    weaknesses:['Pricier than general-purpose chat','Best for marketing, not generic writing'],
    bestFor:'In-house marketing teams, agencies',
    alternatives:['copy','grammarly','claude'] },

  { slug:'copy', name:'Copy.ai', maker:'Copy.ai', cat:'writing', tier:'specialist',
    pricing:'Free · $49/mo · Pro · Enterprise', url:'https://www.copy.ai',
    blurb:'Sales and marketing workflow AI — campaigns, not just copy.',
    summary:'Copy.ai has matured into a GTM (go-to-market) workflow platform — sales sequences, RFP responses, content campaigns, with a workflow builder for automating end-to-end pipelines.',
    strengths:['Workflow automations','Strong GTM templates','Good free tier'],
    weaknesses:['UX has a lot of surface area','Less freeform than chat tools'],
    bestFor:'Sales and marketing ops teams',
    alternatives:['jasper','clay','lindy'] },

  { slug:'sudowrite', name:'Sudowrite', maker:'Sudowrite', cat:'writing', tier:'specialist',
    pricing:'$10 / $22 / $44 per month', url:'https://www.sudowrite.com',
    blurb:'Fiction-writing assistant built by novelists.',
    summary:'Sudowrite is the most thoughtful fiction tool in AI — Story Engine for outlining and drafting full novels, brainstorming, rewriting, and a community that takes craft seriously.',
    strengths:['Built specifically for fiction','Story Engine for long-form structure','Respectful of voice'],
    weaknesses:['Not for non-fiction or marketing','Output still needs human edit'],
    bestFor:'Novelists, screenwriters',
    alternatives:['claude','chatgpt','notion-ai'] },

  { slug:'granola', name:'Granola', maker:'Granola', cat:'writing', tier:'specialist',
    pricing:'Free · $14/mo Pro · Business', url:'https://www.granola.ai',
    blurb:'Meeting notes without a bot in the call.',
    summary:'Granola sits on your laptop, listens to the meeting via system audio, and turns your scribbled notes into clean, structured minutes. No bot joining the call. Calendar-aware and thoughtfully designed.',
    strengths:['No bot in the meeting','Note enhancement, not transcription dumps','Beautiful native macOS app'],
    weaknesses:['Mac-first; Windows newer','Best for 1:1 / small meetings'],
    bestFor:'Founders, PMs, exec roles',
    alternatives:['otter','fireflies','notion-ai'] },

  { slug:'otter', name:'Otter.ai', maker:'Otter', cat:'writing', tier:'leading',
    pricing:'Free · $17/mo Pro · $30/mo Business', url:'https://otter.ai',
    blurb:'The transcription default. Now with an in-meeting AI assistant.',
    summary:'Otter joins Zoom, Meet, and Teams calls, transcribes them in real time, and now ships an AI Chat that answers questions across your meeting library.',
    strengths:['Real-time transcription','Cross-meeting AI Chat','Wide platform coverage'],
    weaknesses:['Bot-in-meeting feels intrusive to some','Long-meeting summaries can blur'],
    bestFor:'Sales, product, anyone living in meetings',
    alternatives:['fireflies','granola','notion-ai'] },

  { slug:'fireflies', name:'Fireflies.ai', maker:'Fireflies', cat:'writing', tier:'leading',
    pricing:'Free · $18/mo · $29/mo · Enterprise', url:'https://fireflies.ai',
    blurb:'Meeting intelligence with deep CRM and analytics integrations.',
    summary:'Fireflies records, transcribes, and analyses meetings — sentiment, topics, action items — and pushes structured outputs into Salesforce, HubSpot, Slack, and Notion.',
    strengths:['Deep CRM sync','Analytics across meeting library','Cross-platform recording'],
    weaknesses:['Bot-in-meeting','Best value at Business+ tier'],
    bestFor:'Revenue and CS teams',
    alternatives:['otter','gong','granola'] },

  /* ============= DESIGN & CREATIVE ============= */
  { slug:'figma-make', name:'Figma Make & AI', maker:'Figma', cat:'design', tier:'frontier',
    pricing:'Bundled with Figma plans', url:'https://www.figma.com/ai',
    blurb:'AI inside the design tool. Generates, edits, and now codes.',
    summary:'Figma’s AI features now span the whole product — first-draft generation in Design, image fill and edits, AI translations, the new Figma Make for prompt-to-prototype, and Sites for AI-assisted publishing.',
    strengths:['Inside the tool designers already use','Make turns prompts into prototypes','Tight design-to-code workflows'],
    weaknesses:['Best with a paid Figma plan','AI features still uneven by surface'],
    bestFor:'Product designers, design teams',
    alternatives:['stitch','v0','framer'] },

  { slug:'canva', name:'Canva Magic Studio', maker:'Canva', cat:'design', tier:'leading',
    pricing:'Free · $15/mo Pro · Teams · Enterprise', url:'https://www.canva.com/magic-studio/',
    blurb:'AI for the 200M+ people who already live in Canva.',
    summary:'Canva’s Magic Studio bundles Magic Write, Magic Design, Magic Edit, video generation (via Veo / Runway integration), and the new AI app builder. The widest-reach creative AI in the world.',
    strengths:['Massive user base and templates','Integrates leading models','Genuinely useful Magic Edit'],
    weaknesses:['Quality ceiling below pro tools','Editor can feel template-shaped'],
    bestFor:'Marketers, small businesses, students',
    alternatives:['figma-make','firefly','gamma'] },

  { slug:'framer', name:'Framer', maker:'Framer', cat:'design', tier:'leading',
    pricing:'Free · $5 / $15 / $30 per site per month', url:'https://www.framer.com',
    blurb:'AI-powered site builder. Designer-grade output, no code.',
    summary:'Framer is the no-code site builder that designers actually respect — Workshop AI, Localize, Translate, and a real CMS. The fastest way to ship a beautiful marketing site.',
    strengths:['Designer-grade output','Real CMS and CDN','Workshop AI for sections / pages'],
    weaknesses:['Not meant for app-grade interactivity','Pricing per site adds up'],
    bestFor:'Designers, founders, marketing teams',
    alternatives:['v0','figma-make','canva'] },

  { slug:'gamma', name:'Gamma', maker:'Gamma', cat:'design', tier:'specialist',
    pricing:'Free · $10/mo Plus · Pro · Teams', url:'https://gamma.app',
    blurb:'AI presentations that actually look good.',
    summary:'Gamma turns prompts and outlines into polished decks, docs, and webpages — with on-brand themes, AI-generated images, and analytics. The default for AI presentations.',
    strengths:['Beautiful default themes','One workflow for decks, docs, and sites','Analytics built in'],
    weaknesses:['Output can read “AI deck-shaped”','Edits less granular than Keynote / Slides'],
    bestFor:'Founders, sales, educators',
    alternatives:['beautiful','canva','figma-make'] },

  { slug:'beautiful', name:'Beautiful.ai', maker:'Beautiful.ai', cat:'design', tier:'specialist',
    pricing:'$12 / $40 / $50 per month', url:'https://www.beautiful.ai',
    blurb:'Smart slide automation for serious teams.',
    summary:'Beautiful.ai is the deck tool for organisations that need brand-locked, on-template, AI-assisted slides at scale — strong for sales orgs and consulting.',
    strengths:['Strong brand controls','Smart slide templates','Team libraries'],
    weaknesses:['Less freeform than Gamma','Pricing aimed at teams'],
    bestFor:'Sales orgs, consultants',
    alternatives:['gamma','canva','figma-make'] },

  { slug:'uizard', name:'Uizard', maker:'Uizard (Miro)', cat:'design', tier:'specialist',
    pricing:'Free · $19/mo · $39/mo · Business', url:'https://uizard.io',
    blurb:'Wireframes and prototypes from screenshots, sketches, or text.',
    summary:'Uizard turns scribbles, screenshots, or prompts into editable wireframes and prototypes in minutes — perfect for early ideation and PRDs.',
    strengths:['Sketch-to-design','Screenshot-to-design','Multi-screen prototypes'],
    weaknesses:['Not meant for high-fidelity polish','Now part of Miro, evolving'],
    bestFor:'PMs, founders, UX researchers',
    alternatives:['stitch','figma-make','galileo'] },

  { slug:'galileo', name:'Galileo AI', maker:'Galileo (Google)', cat:'design', tier:'specialist',
    pricing:'Free · $19/mo · $35/mo', url:'https://www.usegalileo.ai',
    blurb:'High-fidelity UI design from text. Acquired by Google.',
    summary:'Galileo generates clean, high-fidelity UI screens from prompts — Figma-export, design systems, and component editing. Google acquired the team in 2024 and the product continues to ship.',
    strengths:['Beautiful default UI output','Figma export','Generates flows, not just screens'],
    weaknesses:['Roadmap shaped by Google’s plans','Less interactive than Make / Stitch'],
    bestFor:'Founders, designers, fast prototyping',
    alternatives:['stitch','uizard','figma-make'] },

  /* ============= BUSINESS & AUTOMATION ============= */
  { slug:'zapier', name:'Zapier', maker:'Zapier', cat:'business', tier:'frontier',
    pricing:'Free · $19.99/mo · $49/mo · Teams', url:'https://zapier.com',
    blurb:'The workflow automation standard, now with AI agents and Canvas.',
    summary:'Zapier connects 8,000+ apps with no-code automation, and has added Agents, Tables, Interfaces, Chatbots, and Canvas — a full AI workflow studio on top of the original automation pipes.',
    strengths:['Largest integration library by far','AI Agents and Canvas','Tables and Interfaces for full apps'],
    weaknesses:['Pricing scales with task volume','Power users hit ceilings vs n8n / Make'],
    bestFor:'Operators automating real workflows',
    alternatives:['n8n','make','lindy'] },

  { slug:'n8n', name:'n8n', maker:'n8n', cat:'business', tier:'leading',
    pricing:'Free · self-host · Cloud from $20/mo', url:'https://n8n.io',
    blurb:'Open-source, fair-code workflow automation with AI nodes.',
    summary:'n8n is the developer-friendly workflow tool — visual nodes, code blocks, AI agent and LangChain nodes, and a self-host option that’s become a favourite among AI builders.',
    strengths:['Open-source / self-host','First-class AI agent nodes','No per-task pricing on Cloud'],
    weaknesses:['Steeper than Zapier for non-devs','Self-host is your problem'],
    bestFor:'Technical operators and AI builders',
    alternatives:['zapier','make','lindy'] },

  { slug:'make', name:'Make', maker:'Make', cat:'business', tier:'leading',
    pricing:'Free · $9 / $16 / $29 per month', url:'https://www.make.com',
    blurb:'Visual automation with deep iterators and routers.',
    summary:'Make (formerly Integromat) is the visual automation tool for power users — deep branching, iterators, and a tight visual editor that handles workflows Zapier can’t.',
    strengths:['Powerful visual editor','Routers and iterators','Per-operation pricing'],
    weaknesses:['Smaller integration list than Zapier','Steeper learning curve'],
    bestFor:'Power-user operators and consultants',
    alternatives:['zapier','n8n','lindy'] },

  { slug:'clay', name:'Clay', maker:'Clay', cat:'business', tier:'specialist',
    pricing:'Free · $134 / $314 / $720 per month', url:'https://www.clay.com',
    blurb:'AI-powered lead enrichment and outbound at scale.',
    summary:'Clay is a spreadsheet on steroids — pull data from 100+ sources, enrich leads with AI, draft personalised outreach, and ship to your CRM. The most-used tool among modern outbound teams.',
    strengths:['100+ data providers in one','AI-driven personalisation','Workflows for whole GTM motions'],
    weaknesses:['Pricier than basic enrichment tools','Best in the hands of an ops person'],
    bestFor:'Sales ops, RevOps, growth',
    alternatives:['apollo','copy','lindy'] },

  { slug:'apollo', name:'Apollo.io', maker:'Apollo', cat:'business', tier:'leading',
    pricing:'Free · $49 / $79 / $119 per user per month', url:'https://www.apollo.io',
    blurb:'B2B contact data, sequencing, and AI selling assistant in one.',
    summary:'Apollo combines a 275M+ contact database with sequences, dialer, meeting scheduler, and an AI assistant that drafts emails, scores accounts, and runs research.',
    strengths:['Huge contact database','All-in-one sales motion','Strong free tier'],
    weaknesses:['Data freshness varies by region','Heavier than focused tools'],
    bestFor:'SDRs, AEs, founder-led sales',
    alternatives:['clay','gong','lindy'] },

  { slug:'gong', name:'Gong', maker:'Gong', cat:'business', tier:'specialist',
    pricing:'Custom (Enterprise)', url:'https://www.gong.io',
    blurb:'Revenue intelligence from every customer call, email, and deal.',
    summary:'Gong records and analyses every customer interaction to surface deal risk, coaching insights, and forecast accuracy. The category-defining revenue intelligence platform.',
    strengths:['Deepest call analytics in the market','Forecasting and deal warnings','Strong coaching workflows'],
    weaknesses:['Enterprise pricing','Heavy lift to deploy'],
    bestFor:'B2B sales orgs at scale',
    alternatives:['fireflies','apollo','clay'] },

  { slug:'harvey', name:'Harvey', maker:'Harvey', cat:'business', tier:'specialist',
    pricing:'Enterprise (custom)', url:'https://www.harvey.ai',
    blurb:'Domain-specific AI for elite law firms and in-house teams.',
    summary:'Harvey builds models and workflows for legal work — drafting, due diligence, contract analysis, regulatory research — used by a who’s-who of global law firms.',
    strengths:['Legal-domain training','Agent workflows for due diligence','Used by top-tier firms'],
    weaknesses:['Enterprise-only','Not for small practices'],
    bestFor:'Big-law firms, in-house legal',
    alternatives:['hebbia','glean','notion-ai'] },

  { slug:'hebbia', name:'Hebbia', maker:'Hebbia', cat:'business', tier:'specialist',
    pricing:'Enterprise (custom)', url:'https://www.hebbia.com',
    blurb:'Enterprise knowledge retrieval for finance and pro services.',
    summary:'Hebbia’s Matrix product runs structured queries across an organisation’s entire knowledge base — every PDF, deck, transcript, and database — for finance, consulting, and law.',
    strengths:['Cross-document structured Q&A','Custom enterprise deployments','Strong audit trail'],
    weaknesses:['Enterprise pricing','Not for individuals'],
    bestFor:'Investment, consulting, legal',
    alternatives:['glean','harvey','notebooklm'] },

  { slug:'glean', name:'Glean', maker:'Glean', cat:'business', tier:'specialist',
    pricing:'Enterprise (custom)', url:'https://www.glean.com',
    blurb:'Enterprise search and AI assistant across all your work apps.',
    summary:'Glean is the AI search and assistant layer that sits across Google Drive, Slack, Notion, Salesforce, GitHub, and 100+ more — answering company-specific questions with citations.',
    strengths:['Connects across enterprise tools','Strong permissions model','Custom agents on top of corpus'],
    weaknesses:['Enterprise procurement cycle','Best with broad app footprint'],
    bestFor:'Knowledge-intensive enterprises',
    alternatives:['hebbia','notion-ai','copilot'] },

  { slug:'relevance-ai', name:'Relevance AI', maker:'Relevance AI', cat:'business', tier:'specialist',
    pricing:'Free · $19/mo · $99/mo · Enterprise', url:'https://relevanceai.com',
    blurb:'Build and deploy an AI workforce of role-based agents.',
    summary:'Relevance AI lets you compose teams of agents — “Bosh” the SDR, “Lima” the analyst — with tools, memory, and triggers, then run them on your data with a no-code studio.',
    strengths:['No-code agent teams','Visual tool builder','Big template library'],
    weaknesses:['Less granular than Python frameworks','Custom integrations take work'],
    bestFor:'Ops and revenue teams',
    alternatives:['lindy','crewai','zapier'] },

  /* ============= INFRA & PLATFORMS ============= */
  { slug:'huggingface', name:'Hugging Face', maker:'Hugging Face', cat:'infra', tier:'frontier',
    pricing:'Free · Pro · Enterprise', url:'https://huggingface.co',
    blurb:'The model hub. Plus datasets, Spaces, and the Open LLM Leaderboard.',
    summary:'Hugging Face is the npm of machine learning — 1M+ models, 200k+ datasets, Spaces for hosting demos, the Open LLM Leaderboard for ranking models, Inference Endpoints for production, and a thriving community.',
    strengths:['Largest model and dataset hub','Open LLM Leaderboard for unbiased ranking','Spaces, Datasets, Endpoints, AutoTrain'],
    weaknesses:['UI can feel sprawling','Some hubs lack moderation'],
    bestFor:'Anyone doing serious ML work',
    alternatives:['replicate','modal','together'] },

  { slug:'replicate', name:'Replicate', maker:'Replicate', cat:'infra', tier:'leading',
    pricing:'Pay per second of compute', url:'https://replicate.com',
    blurb:'Run any open model via a clean API. Or deploy your own.',
    summary:'Replicate lets you call thousands of open-source models through a single API — image, video, audio, language, vision — with autoscaling GPUs you don’t manage.',
    strengths:['Huge catalogue of pre-deployed models','Per-second pricing','Easy fine-tuning'],
    weaknesses:['Cold starts on rare models','Bills surprise the unprepared'],
    bestFor:'Builders who don’t want to manage GPUs',
    alternatives:['fal','huggingface','modal'] },

  { slug:'fal', name:'Fal.ai', maker:'Fal', cat:'infra', tier:'leading',
    pricing:'Pay per second · monthly plans', url:'https://fal.ai',
    blurb:'The fastest inference platform for image, video, and audio.',
    summary:'Fal.ai obsesses over latency — sub-second image generation, real-time video, and a clean serverless API for the leading open and licensed models. The default for any product where speed matters.',
    strengths:['Lowest latency in the category','Real-time models hosted','Strong developer ergonomics'],
    weaknesses:['Pricing complex at scale','Less general than Replicate'],
    bestFor:'Real-time creative product builders',
    alternatives:['replicate','together','modal'] },

  { slug:'together', name:'Together AI', maker:'Together', cat:'infra', tier:'leading',
    pricing:'Pay per token · dedicated', url:'https://www.together.ai',
    blurb:'High-throughput hosting for open models. Cheap, fast, fine-tunable.',
    summary:'Together hosts hundreds of open-weight LLMs and image models with serverless and dedicated inference — and offers fine-tuning and reasoning APIs at competitive prices.',
    strengths:['Cheapest hosting for many open models','Fine-tuning and reasoning APIs','Dedicated capacity available'],
    weaknesses:['Quality only as good as the open model','Less consumer-facing'],
    bestFor:'Production teams shipping on open models',
    alternatives:['replicate','openrouter','fal'] },

  { slug:'openrouter', name:'OpenRouter', maker:'OpenRouter', cat:'infra', tier:'leading',
    pricing:'Pay per token · no monthly', url:'https://openrouter.ai',
    blurb:'One API key, every frontier and open model.',
    summary:'OpenRouter is a router across 300+ models from every major lab — Anthropic, OpenAI, Google, xAI, DeepSeek, Mistral, Meta, and more — billed under a single account with smart fallbacks.',
    strengths:['One key for every model','Automatic fallbacks and cost optimisation','Public model leaderboards'],
    weaknesses:['Adds a layer of latency','Margin sits between you and the lab'],
    bestFor:'Builders evaluating or routing across models',
    alternatives:['together','replicate','vercel-ai'] },

  { slug:'pinecone', name:'Pinecone', maker:'Pinecone', cat:'infra', tier:'specialist',
    pricing:'Free · usage-based · Enterprise', url:'https://www.pinecone.io',
    blurb:'The managed vector database. Battle-tested at enterprise scale.',
    summary:'Pinecone is the most-used managed vector DB in production — fast, simple, and now offering serverless and Inference for embeddings + reranking in one stack.',
    strengths:['Simple and fast','Serverless option','Inference and reranking included'],
    weaknesses:['Closed-source','Costs add up at heavy scale'],
    bestFor:'Production RAG at scale',
    alternatives:['weaviate','llamaindex','cohere'] },

  { slug:'weaviate', name:'Weaviate', maker:'Weaviate', cat:'infra', tier:'open',
    pricing:'Open-source · Cloud from $25/mo', url:'https://weaviate.io',
    blurb:'Open-source vector database with strong hybrid search.',
    summary:'Weaviate is the leading open-source vector DB — hybrid search, modules for embedding and reranking, and a managed cloud option for teams who don’t want to self-host.',
    strengths:['Open-source','Hybrid (BM25 + vector) search','Built-in embedding modules'],
    weaknesses:['More moving parts than Pinecone','Self-host needs care'],
    bestFor:'OSS-first teams, on-prem RAG',
    alternatives:['pinecone','llamaindex','cohere'] },

  { slug:'modal', name:'Modal', maker:'Modal', cat:'infra', tier:'specialist',
    pricing:'Free credits · per-second compute', url:'https://modal.com',
    blurb:'Serverless GPU infra that feels like writing Python.',
    summary:'Modal makes serverless GPUs pleasant — write a Python function, decorate it, and Modal handles containers, autoscaling, and storage. The default cloud for ML teams that don’t want a Kubernetes habit.',
    strengths:['Python-first developer experience','Per-second GPU billing','Volumes, secrets, and queues built in'],
    weaknesses:['Single-vendor lock-in','Cold starts vary by GPU'],
    bestFor:'ML engineers shipping inference / training jobs',
    alternatives:['replicate','fal','together'] },

  { slug:'llamaindex', name:'LlamaIndex', maker:'LlamaIndex', cat:'infra', tier:'open',
    pricing:'Open-source · LlamaCloud usage-based', url:'https://www.llamaindex.ai',
    blurb:'The RAG and agent framework for production-grade data work.',
    summary:'LlamaIndex is the leading framework for RAG and document-heavy agents — connectors, parsing, query engines, and the managed LlamaCloud + LlamaParse for production document pipelines.',
    strengths:['Strong RAG and document parsing','LlamaParse for messy PDFs','Both Python and TypeScript SDKs'],
    weaknesses:['Surface area can overlap with LangChain','Best for data-heavy use cases'],
    bestFor:'RAG, document, and knowledge-base builders',
    alternatives:['langchain','vercel-ai','huggingface'] },

  { slug:'cohere', name:'Cohere', maker:'Cohere', cat:'infra', tier:'specialist',
    pricing:'Free trial · usage-based · enterprise', url:'https://cohere.com',
    blurb:'Enterprise LLMs, embeddings, and reranking with a privacy posture.',
    summary:'Cohere ships the Command family of LLMs, the best-in-class Embed and Rerank models, and a North platform for secure enterprise AI — VPC, on-prem, and air-gapped deployments included.',
    strengths:['Best-in-class Rerank models','Strong privacy / deployment story','Enterprise sales motion'],
    weaknesses:['Less consumer presence','Behind frontier on raw chat quality'],
    bestFor:'Regulated enterprises, search teams',
    alternatives:['huggingface','together','openrouter'] },

  { slug:'vercel-ai', name:'Vercel AI Gateway & SDK', maker:'Vercel', cat:'infra', tier:'specialist',
    pricing:'Free · usage-based', url:'https://vercel.com/ai',
    blurb:'TypeScript-first SDK plus a unified gateway for every model.',
    summary:'Vercel’s AI SDK is the de facto TypeScript way to build streaming AI apps; the new AI Gateway sits in front and lets you call any provider with one key, with caching, rate-limits, and observability included.',
    strengths:['Best TS streaming primitives','One key for every provider','Tight Next.js integration'],
    weaknesses:['Best for JS / TS stacks','Gateway adds slight overhead'],
    bestFor:'TypeScript and Next.js teams',
    alternatives:['openrouter','langchain','llamaindex'] },
];

/* ============= STACKS (curated bundles) ============= */
const STACKS = [
  { slug:'developer', label:'STACK № 01', name:'The Developer',
    desc:'For the engineer who ships. Coding agent, reasoning model, research, and review — the stack most senior engineers actually use.',
    tools:['claude-code','cursor','perplexity','v0'], cost:'$60' },
  { slug:'creator', label:'STACK № 02', name:'The Creator',
    desc:'For the solo creative. Image, video, music, and voice — everything you need to go from idea to finished piece in a day.',
    tools:['midjourney','runway','suno','elevenlabs','krea'], cost:'$95' },
  { slug:'founder', label:'STACK № 03', name:'The Founder',
    desc:'For the one-person company. Research, writing, outreach, automation, and agents — the operating system for a solo business.',
    tools:['chatgpt','manus','notion-ai','zapier','clay'], cost:'$120' },
  { slug:'designer', label:'STACK № 04', name:'The Designer',
    desc:'For the product designer. Generation, refinement, prototypes, and code hand-off — the modern design pipeline.',
    tools:['figma-make','midjourney','recraft','stitch','v0'], cost:'$75' },
  { slug:'researcher', label:'STACK № 05', name:'The Researcher',
    desc:'For analysts and academics. Cited answers, source synthesis, deep reads, and audio overviews — the modern thinking workbench.',
    tools:['perplexity','notebooklm','elicit','claude','exa'], cost:'$50' },
  { slug:'marketer', label:'STACK № 06', name:'The Marketer',
    desc:'For brand and growth. Copy, image, video, decks, and sequencing — a full content engine in five tools.',
    tools:['jasper','canva','runway','gamma','clay'], cost:'$110' },
  { slug:'agent-builder', label:'STACK № 07', name:'The Agent Builder',
    desc:'For developers shipping agents. Framework, observability, retrieval, and inference — the production agent stack.',
    tools:['langgraph','langchain','llamaindex','tavily','openrouter'], cost:'API-only' },
  { slug:'voice-team', label:'STACK № 08', name:'The Voice Team',
    desc:'For anyone shipping spoken AI. Best TTS, lowest-latency real-time, telephony, and call infra in one bundle.',
    tools:['elevenlabs','cartesia','vapi','bland','openai-voice'], cost:'Usage-based' },
];

/* ============= NEW & UPDATED feed (manually curated) ============= */
const NEW_UPDATES = [
  { slug:'claude-code', headline:'Claude Code lands on the web — and breaks 80% on SWE-bench Verified.', date:'2026-04', kind:'major-update' },
  { slug:'veo', headline:'Veo 3.1 ships native synced audio across every generation.', date:'2026-04', kind:'major-update' },
  { slug:'higgsfield', headline:'Higgsfield adds full identity-locked character video.', date:'2026-03', kind:'new' },
  { slug:'stitch', headline:'Google Stitch opens to the public — prompt-to-UI from Google Labs.', date:'2026-03', kind:'new' },
  { slug:'cursor', headline:'Cursor 2.0: Plan mode, multi-agent runs, and a calmer Composer.', date:'2026-03', kind:'major-update' },
  { slug:'perplexity-assistant', headline:'Comet ships on macOS and Windows.', date:'2026-02', kind:'new' },
  { slug:'lyria', headline:'Lyria RealTime arrives in Vertex — adaptive music, finally.', date:'2026-02', kind:'new' },
  { slug:'manus', headline:'Manus opens credits-based access to all users globally.', date:'2026-01', kind:'major-update' },
  { slug:'openrouter', headline:'OpenRouter passes 300 models with auto-fallbacks.', date:'2026-01', kind:'milestone' },
  { slug:'fal', headline:'Fal.ai launches sub-second video generation.', date:'2025-12', kind:'major-update' },
];

/* expose */
if (typeof window !== 'undefined') {
  window.OMNI = { TOOLS, CATEGORIES, TIERS, STACKS, NEW_UPDATES };
}
